[project]
name = "asteroids"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pygame==2.6.1",
]

[dependency-groups]
dev = [
    "python-lsp-server>=1.14.0",
    "ruff>=0.14.14",
]
